version: "3.8"

services:

  pokemon-db:
    container_name: "pokemon-db"
    image: mysql:latest
    volumes:
    - type: volume
      source: pokemon-volume
      target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:

  service-1:
    container_name: "service-1"
    image: gavthetallone/service-1
    build: ./service_1
    environment:
      DATABASE_URI:
    restart: on-failure
    deploy:
      replicas: 10

  service-2:
    container_name: "service-2"
    image: gavthetallone/service-2
    build: ./service_2
    deploy:
      replicas: 10

  service-3:
    container_name: "service-3"
    image: gavthetallone/service-3
    build: ./service_3
    deploy:
      replicas: 10

  service-4:
    container_name: "service-4"
    image: gavthetallone/service-4
    build: ./service_4
    deploy:
      replicas: 10

  pokemon-proxy:
    container_name: pokemon-proxy
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - service-1

volumes:
  pokemon-volume: