all:
  hosts:
    swarm-master:
    load-balancer:
  children:
    workers:
      hosts:
        swarm-worker:
        swarm-worker-2:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'