- hosts: load-balancer
  become: true
  roles:
    - Configure NGINX

- hosts:
    - swarm-master
    - workers
  become: true
  roles:
    - Install Docker

- hosts: swarm-master
  become: true
  roles:
    - Initialise Swarm

- hosts: workers
  become: true
  roles:
    - Join Swarm